src/main/java/com/creddit/credditmainserver/api/MemberApiController.java, src/main/java/com/creddit/credditmainserver/repository/MemberRepository.java, src/main/java/com/creddit/credditmainserver/service/MemberService.java
이메일 존재 시 true 반환, 존재하지 않을 시 false 반환
닉네임 존재 시 true 반환, 존재하지 않을 시 false 반환
=> feature: 이메일, 닉네임 중복 체크

src/main/java/com/creddit/credditmainserver/api/MemberApiController.java, src/main/java/com/creddit/credditmainserver/domain/Member.java, src/main/java/com/creddit/credditmainserver/service/MemberService.java
char type의 delYn을 boolean type의 activated으로 변경
=> refactor: Member 엔티티의 delYn 컬럼을  activated로 변경

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, src/main/java/com/creddit/credditmainserver/api/PostApiController.java, src/main/java/com/creddit/credditmainserver/controller/PostController.java, src/main/java/com/creddit/credditmainserver/domain/Post.java, src/main/java/com/creddit/credditmainserver/dto/request/PostSaveRequestDto.java, src/main/java/com/creddit/credditmainserver/dto/request/PostUpdateRequestDto.java, src/main/java/com/creddit/credditmainserver/service/PostService.java, src/test/java/com/creddit/credditmainserver/api/PostApiControllerTest.java, src/test/java/com/creddit/credditmainserver/service/PostServiceTest.java
=> feat: 글 생성, 수정, 삭제, 조회

src/main/java/com/creddit/credditmainserver/api/MemberApiController.java
=> style: print 코드 삭제

src/main/java/com/creddit/credditmainserver/api/PostApiController.java, src/main/java/com/creddit/credditmainserver/controller/PostController.java, src/main/java/com/creddit/credditmainserver/domain/Comment.java, src/main/java/com/creddit/credditmainserver/domain/Like.java, src/main/java/com/creddit/credditmainserver/domain/Member.java, src/main/java/com/creddit/credditmainserver/domain/Post.java, src/main/java/com/creddit/credditmainserver/dto/request/PostSaveRequestDto.java, src/main/java/com/creddit/credditmainserver/dto/request/PostUpdateRequestDto.java, src/main/java/com/creddit/credditmainserver/dto/response/PostResponseDto.java, src/main/java/com/creddit/credditmainserver/service/PostService.java, src/test/java/com/creddit/credditmainserver/api/PostApiControllerTest.java, src/test/java/com/creddit/credditmainserver/service/PostServiceTest.java
- 테스트 코드 작성 및 수정
- PostController, PostApiController 작성, 수정 URI 변경
- Post dto들 수정
- Post, Like, Comment 컬럼 수정
- Member에 있던 양방향 연관관계 삭제
=> test: PostApiControllerTest 테스트 코드 작성, PostServiceTest 수정

src/main/java/com/creddit/credditmainserver/controller/AuthController.java, src/main/java/com/creddit/credditmainserver/dto/request/MemberRequestDto.java
-이메일 규격에 맞지 않거나 비밀번호의 규칙에 맞지 않거나 닉네임의 규칙에 맞지 않을 시 오류 메시지 반환
=> feature: 이메일, 비밀번호, 닉네임 Validation 로직 추가

src/main/resources/application.yml
- jwt설정 앞에 white-space로 안해 오류가 발생하여 white space삭제
=> fix: white-space로 인한 오류 해결

src/main/java/com/creddit/credditmainserver/login/jwt/TokenProvider.java
- 입력받은 토큰이 사용가능한 토큰일 경우 return true
=> fix: 입력받은 토큰이 사용가능한 토큰일 경우 return true

src/main/java/com/creddit/credditmainserver/api/ProfileApiController.java, src/main/java/com/creddit/credditmainserver/domain/Member.java, src/main/java/com/creddit/credditmainserver/dto/request/ProfileRequestDto.java, src/main/java/com/creddit/credditmainserver/dto/response/ProfileResponseDto.java, src/main/java/com/creddit/credditmainserver/service/ProfileService.java
- 저장: 프로필의 사진, 자기소개를 저장
- 출력: 프로필의 사진, 자기소개, 닉네임을 출력
=> feature: 프로필 출력 및 저장 기능

src/main/java/com/creddit/credditmainserver/login/jwt/JwtFilter.java, src/main/java/com/creddit/credditmainserver/login/jwt/TokenProvider.java
- Bearer Type으로 전달할 때 "bearer"이 아닌"Bearer"으로 전달하므로 "bearer"을 "Bearer"로 수정
=> fix: 토큰을 전달할 때 "bearer"로 전달해 생기는 오류 해결

src/main/java/com/creddit/credditmainserver/api/ProfileApiController.java, src/main/java/com/creddit/credditmainserver/domain/Member.java, src/main/java/com/creddit/credditmainserver/dto/request/ProfileRequestDto.java, src/main/java/com/creddit/credditmainserver/dto/response/ProfileResponseDto.java, src/main/java/com/creddit/credditmainserver/service/ProfileService.java
=> feature: 프로필에 사진 추가 출력 기능

src/main/java/com/creddit/credditmainserver/domain/Member.java, src/main/java/com/creddit/credditmainserver/dto/response/ProfileResponseDto.java
=> feature: 프로필에 아이디 생성 날짜 추가

src/main/java/com/creddit/credditmainserver/api/ProfileApiController.java
- 출력 컨트롤러 PostMapping에서 GetMapping으로 수정
=> fix: 출력 컨트롤러 PostMapping에서 GetMapping으로 수정

src/main/java/com/creddit/credditmainserver/api/MemberApiController.java, src/main/java/com/creddit/credditmainserver/dto/response/MemberResponseDto.java, src/main/java/com/creddit/credditmainserver/service/MemberService.java
=> feature: 닉네임 변경 기능 추가

src/main/java/com/creddit/credditmainserver/service/AuthService.java
=> refactor: 회원가입 코드 간소화

src/main/java/com/creddit/credditmainserver/dto/response/PostResponseDto.java
- PostResponseDto에 isLiked 필드 추가
- 응답 시 현재 로그인한 사용자가 해당 글에 좋아요를 눌렀는지 파악하기 위함
=> feat: PostResponseDto에 isLiked 필드 추가

src/main/java/com/creddit/credditmainserver/dto/response/CommentResponseDto.java
- feat: commentResponseDto에 isLiked 필드 추가
- 응답 시 현재 로그인한 사용자가 해당 댓글에 좋아요를 눌렀는지 파악하기 위함
=> feat: commentResponseDto에 isLiked 필드 추가

src/main/java/com/creddit/credditmainserver/dto/response/CommentResponseDto.java, src/main/java/com/creddit/credditmainserver/dto/response/LikeResponseDto.java, src/main/java/com/creddit/credditmainserver/dto/response/MemberResponseDto.java, src/main/java/com/creddit/credditmainserver/dto/response/PostResponseDto.java
- MemberResponseDto @Builder 삭제
- 다른 Dto에서 MemberResponseDto @builder 대신 생성자 사용
=> Feature post

src/main/java/com/creddit/credditmainserver/domain/Member.java
- createdDate가 null로 들어가는 오류 해결
=> fix: createdDate가 null로 들어가는 오류 해결

src/main/java/com/creddit/credditmainserver/api/ProfileApiController.java, src/main/java/com/creddit/credditmainserver/domain/Image.java
- 이미지를 넣지 않았을 때 S3에 0KB 파일이 업로드 되지 않도록 수정
=> perf: 이미지를 넣지 않았을 때 S3에 0KB 파일이 업로드 되지 않도록 수정

src/main/java/com/creddit/credditmainserver/api/MemberApiController.java, src/main/java/com/creddit/credditmainserver/domain/Follower.java, src/main/java/com/creddit/credditmainserver/repository/FollowRepository.java, src/main/java/com/creddit/credditmainserver/repository/MemberRepository.java, src/main/java/com/creddit/credditmainserver/service/MemberService.java
=> feature: 팔로우 팔로우 해제 기능 추가

src/main/java/com/creddit/credditmainserver/api/MemberApiController.java, src/main/java/com/creddit/credditmainserver/domain/Follower.java, src/main/java/com/creddit/credditmainserver/repository/FollowRepository.java, src/main/java/com/creddit/credditmainserver/service/MemberService.java
- follow 테이블과 member 테이블의 연관관계 추가
=> refactor: follow 테이블과 member 테이블의 연관관계 추가

src/main/java/com/creddit/credditmainserver/service/MemberService.java
=> fix: 없는 follow 삭제 요청시 예외처리

build.gradle, src/main/java/com/creddit/credditmainserver/api/MemberApiController.java, src/main/java/com/creddit/credditmainserver/dto/request/PasswordRequestDto.java, src/main/java/com/creddit/credditmainserver/service/EmailSendService.java, src/main/java/com/creddit/credditmainserver/service/MemberService.java, src/main/resources/application.yml
- 이메일 주소를 입력하면 해당 이메일로 임시비밀번호를 전송 
- 임시비밀번호로 로그인 후 비밀번호 재설정
=> feature: 비밀번호 찾기 기능

src/main/java/com/creddit/credditmainserver/api/MemberApiController.java
=> chore: swagger 설명 추가

src/main/java/com/creddit/credditmainserver/dto/response/PostResponseDto.java, src/main/java/com/creddit/credditmainserver/service/PostService.java
- 상세 글 조회 API 응답 데이터 중 댓글 리스트 삭제
=> refactor: 상세 글 조회 API 응답 데이터 중 댓글 리스트 삭제

src/main/java/com/creddit/credditmainserver/api/PostApiController.java, src/main/java/com/creddit/credditmainserver/domain/Post.java, src/main/java/com/creddit/credditmainserver/repository/PostRepository.java, src/main/java/com/creddit/credditmainserver/service/PostService.java, src/test/java/com/creddit/credditmainserver/service/PostServiceTest.java
- 글 수정 시 DTO만 보낼 때 기존 이미지 유지하고 제목&내용만 변경
- 빈 파일 보낼 때 이미지 삭제
=> refactor: 글 수정 시 DTO만 보낼 때 기존 이미지 유지하고 제목&내용만 변경, 빈 파일 보낼 때 이미지 삭제

src/main/java/com/creddit/credditmainserver/api/CommentApiController.java, src/main/java/com/creddit/credditmainserver/api/PostApiController.java, src/main/java/com/creddit/credditmainserver/service/CommentService.java, src/main/java/com/creddit/credditmainserver/service/PostService.java, src/test/java/com/creddit/credditmainserver/service/PostServiceTest.java
=> feat: 글, 댓글 수정&삭제 시 작성자 체크

src/main/java/com/creddit/credditmainserver/api/ProfileApiController.java, src/main/java/com/creddit/credditmainserver/service/ProfileService.java
=> feature: 닉네임을 통한 프로필 출력 기능

src/main/java/com/creddit/credditmainserver/api/PostApiController.java, src/main/java/com/creddit/credditmainserver/dto/response/PostResponseDto.java, src/main/java/com/creddit/credditmainserver/repository/PostRepository.java, src/main/java/com/creddit/credditmainserver/service/PostService.java
- 특정 유저 글 조회 시 정렬 기준 추가(최신, 좋아요)
- 글 검색 시 정렬 기준 추가(최신, 좋아요, 팔로잉)
- 글 조회 시 닉네임으로 좋아요 체크
=> refactor: 유저 글 조회, 글 검색 시 정렬 기준 추가

src/main/java/com/creddit/credditmainserver/api/MemberApiController.java, src/main/java/com/creddit/credditmainserver/controller/AuthController.java, src/main/java/com/creddit/credditmainserver/domain/Member.java, src/main/java/com/creddit/credditmainserver/domain/ProviderType.java, src/main/java/com/creddit/credditmainserver/dto/request/MemberRequestDto.java, src/main/java/com/creddit/credditmainserver/dto/request/SocialLoginRequestDto.java, src/main/java/com/creddit/credditmainserver/service/AuthService.java, src/main/java/com/creddit/credditmainserver/service/EmailSendService.java, src/main/java/com/creddit/credditmainserver/service/MemberService.java
- 프론트로부터 회원의 이메일주소와 이름을 받아와 기존의 회원이면 로그인 서비스를
기존의 회원이 아니면 회원가입을 자동으로 진행하고 로그인 서비스를 제공
=> feature: 소셜 로그인 기능

src/main/java/com/creddit/credditmainserver/service/PostService.java
=>  fix: 글 번호가 아닌 작성자 아이디 가져오도록 수정

src/main/java/com/creddit/credditmainserver/dto/request/MemberRequestDto.java
=> fix: 회원가입 데이터 바인딩할 때 나는 오류 해결

src/main/java/com/creddit/credditmainserver/dto/request/MemberRequestDto.java
=> fix: 회원가입 시 닉네임에 대문자가 입력되도록 수정

src/main/java/com/creddit/credditmainserver/config/SecurityConfig.java
=> feat: corsConfiguration에 allowedOrigin 추가
